### ISSUE TITLE
Date locale for measurement presented to the user

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/eitwid#22]
The question is which date show to the user. Possible options:
  * using user locales
  * using levee locales

@dharezlak, @balis, @bwilk what is your opinion?

**Comment by dharezlak** [comment]
I would go with showing always levee's local time indicating which time zone this is (e.g in the description of the X axis). However, what will be done with readings that fall into the summer/winter time change delay is an open question :)

**Comment by mkasztelnik** [comment]
I believe this is already solved by introducing timestamp with timezone in DAP and correct conversion of the data string into `Data` object in UI.

**Comment by dharezlak** [comment]
Don't think so. The user still does not know what time they see in the charts. As commented previously indication which time zone the time is formatted with should be given (e.g. in the legend).

**Comment by dharezlak** [comment]
Also, the dates displayed by the slider popup are not internationalized. The date should be displayed in the polish date format.
![screenshot from 2015-11-05 22 13 11](https://cloud.githubusercontent.com/assets/1506876/10981894/98f158d4-840a-11e5-8296-d443efba6bcb.png)

**Comment by dharezlak** [comment]
If we assume that we always show user's local time everywhere in the UI we do not need to provide any time zone information (currently sliders show local time zone info while charts do not show it which introduces incoherencyt). Another thing we should do is to use localized time and date formats. GWT has a nice utility for this. Using `DateTimeFormat.getFormat(PredefinedFormat.DATE_TIME_MEDIUM).format(new Date())` for polish locale will yield `1 lut 2016, 10:40:38` while for english `Feb 1, 2016, 10:52:11 AM`. Any other locale should be processed accordingly.
